apiVersion: operator.ibm.com/v1alpha1
kind: MeteringMultiCloudUI
metadata:
  name: meteringmcmui
spec:
  version: "3.5.0"
  imageRegistry: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
  replicas: 3
  iamNamespace: kube-system
  ingressNamespace: kube-system
  commonHeaderNamespace: kube-system
  mongodb:
    host: mongodb.kube-system.svc.cluster.local
    port: 27017
    usernameSecret: icp-mongodb-admin
    usernameKey: user
    passwordSecret: icp-mongodb-admin
    passwordKey: password
    clustercertssecret: cluster-ca-cert
    clientcertssecret: icp-mongodb-client-cert
