apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: meteringmulticlouduis.operator.ibm.com
  labels:
    app.kubernetes.io/instance: "ibm-metering-operator"
    app.kubernetes.io/managed-by: "ibm-metering-operator"
    app.kubernetes.io/name: "ibm-metering"
spec:
  group: operator.ibm.com
  names:
    kind: MeteringMultiCloudUI
    listKind: MeteringMultiCloudUIList
    plural: meteringmulticlouduis
    singular: meteringmulticloudui
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MeteringMultiCloudUI is the Schema for the meteringmulticlouduis
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MeteringMultiCloudUISpec defines the desired state of MeteringMultiCloudUI
          properties:
            imageRegistry:
              type: string
            imageTagPostfix:
              type: string
            mongodb:
              description: MeteringSpecMongoDB defines the MongoDB configuration in
                all the Metering specs
              properties:
                clientcertssecret:
                  type: string
                clustercertssecret:
                  type: string
                host:
                  type: string
                passwordKey:
                  type: string
                passwordSecret:
                  type: string
                port:
                  type: integer
                usernameKey:
                  type: string
                usernameSecret:
                  type: string
              required:
              - clientcertssecret
              - clustercertssecret
              - host
              - passwordKey
              - passwordSecret
              - port
              - usernameKey
              - usernameSecret
              type: object
            replicas:
              format: int32
              type: integer
            ui:
              description: MeteringSpecUI defines the UI configuration in the MeteringUI
                and MeteringMultiCloudUI specs
              properties:
                apikeySecret:
                  type: string
                commonHeaderNamespace:
                  type: string
                iamNamespace:
                  type: string
                ingressNamespace:
                  type: string
                platformOidcSecret:
                  type: string
                resources:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
              type: object
            version:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - mongodb
          - replicas
          - version
          type: object
        status:
          description: MeteringStatus defines the observed state of each Metering
            service
          properties:
            podNames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                PodNames are the names of the metering pods'
              items:
                type: string
              type: array
            versions:
              properties:
                reconciled:
                  type: string
              required:
              - reconciled
              type: object
          required:
          - podNames
          - versions
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
